const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.InstantGamesBridge,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.InstantGamesBridge.Acts.ShowBanner
	];
};
self.C3_JsPropNameTable = [
	{razmer: 0},
	{kolvo: 0},
	{bgsprite: 0},
	{menubt: 0},
	{Text2: 0},
	{nizkiy: 0},
	{nizkiy2: 0},
	{Touch: 0},
	{firework: 0},
	{Sprite: 0},
	{Text: 0},
	{Text3: 0},
	{sh1: 0},
	{sh2: 0},
	{Sine: 0},
	{croco1: 0},
	{croco2: 0},
	{crocoravno: 0},
	{food13: 0},
	{food46: 0},
	{z24: 0},
	{z56: 0},
	{crocoYes: 0},
	{Audio: 0},
	{eng: 0},
	{rus: 0},
	{Text4: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite2: 0},
	{ravno: 0},
	{ravno2: 0},
	{shelf: 0},
	{Text5: 0},
	{"13pears": 0},
	{"45apples": 0},
	{apple: 0},
	{pear: 0},
	{"56pears": 0},
	{"45apples2": 0},
	{"23pineapples": 0},
	{"45bananas": 0},
	{banana: 0},
	{pineapple: 0},
	{"34pineapples": 0},
	{"12bananas": 0},
	{vbt: 0},
	{tolst: 0},
	{tolst2: 0},
	{dlin: 0},
	{dlin2: 0},
	{GamePush: 0},
	{Sprite3: 0},
	{InstantGamesBridge: 0}
];

self.InstanceType = {
	razmer: class extends self.ITextInstance {},
	kolvo: class extends self.ITextInstance {},
	bgsprite: class extends self.ISpriteInstance {},
	menubt: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	nizkiy: class extends self.ISpriteInstance {},
	nizkiy2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	firework: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	sh1: class extends self.ISpriteInstance {},
	sh2: class extends self.ISpriteInstance {},
	croco1: class extends self.ISpriteInstance {},
	croco2: class extends self.ISpriteInstance {},
	crocoravno: class extends self.ISpriteInstance {},
	food13: class extends self.ISpriteInstance {},
	food46: class extends self.ISpriteInstance {},
	z24: class extends self.ISpriteInstance {},
	z56: class extends self.ISpriteInstance {},
	crocoYes: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	eng: class extends self.ISpriteInstance {},
	rus: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ravno: class extends self.ISpriteInstance {},
	ravno2: class extends self.ISpriteInstance {},
	shelf: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	_13pears: class extends self.ISpriteInstance {},
	_45apples: class extends self.ISpriteInstance {},
	apple: class extends self.ISpriteInstance {},
	pear: class extends self.ISpriteInstance {},
	_56pears: class extends self.ISpriteInstance {},
	_45apples2: class extends self.ISpriteInstance {},
	_23pineapples: class extends self.ISpriteInstance {},
	_45bananas: class extends self.ISpriteInstance {},
	banana: class extends self.ISpriteInstance {},
	pineapple: class extends self.ISpriteInstance {},
	_34pineapples: class extends self.ISpriteInstance {},
	_12bananas: class extends self.ISpriteInstance {},
	vbt: class extends self.ITextInstance {},
	tolst: class extends self.ISpriteInstance {},
	tolst2: class extends self.ISpriteInstance {},
	dlin: class extends self.ISpriteInstance {},
	dlin2: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	InstantGamesBridge: class extends self.IInstance {}
}